name: Plan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [
          ./,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Check diff
      #   id: diff
      #   uses: technote-space/get-diff-action@v4.0.2
      #   with:
      #     PATTERNS: |
      #       modules/**/*.tf
      #       ${{ matrix.dir }}/**/*.tf

      - name: Configure aws credentials
        # if: steps.diff.outputs.diff
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup terraform
        # if: steps.diff.outputs.diff
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 1.2.7

      - name: Check format
        id: fmt
        # if: steps.diff.outputs.diff
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.dir }}
        continue-on-error: true

      - name: Initialize
        id: init
        # if: steps.diff.outputs.diff
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Download modules
        # if: steps.diff.outputs.diff
        run: terraform get
        working-directory: ${{ matrix.dir }}

      - name: Validate
        # if: steps.diff.outputs.diff
        run: terraform validate
        working-directory: ${{ matrix.dir }}

      - name: Plan
        # if: steps.diff.outputs.diff
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ matrix.dir }}
        continue-on-error: true
